server:
 promocionURL: http://poct-promocion:8083/api/v1/comercios/
 clienteURL1: http://localhostt:7777/credit-charge-card/sd-reference-id/credit-charge-card-fulfilment-arrangement/
 clienteURL2: http://localhost:7777/customer-reference-data-management/sd-reference-id/customer-reference-data-directory-entry/
 clienteURL3: http://localhost:7777/party-data-management/sd-reference-id/party-directory-entry/1
 
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

spring:
  profiles:
    active: dev
