elasticsearchURL: http://10.42.1.32:9200
elasticsearchUser: elastic
elasticsearchPass: vo2PwXh7iWSrz37Pc7sI
coreValidatorURL: http://172.20.218.10:30024
index: filebeat-7.10.0-2021.03.03-000001
restTemplateTimeout: 120000
#   Config Mongo
mongo.username: admin
mongo.password: mongoPassword
mongo.database: db_bian
mongo.host: 172.20.218.10
mongo.port: 30044
mongo.connectionTimeoutMS: 30000
mongo.socketTimeoutMS: 60000
mongo.authSource: admin
mongo.w: majority
mongo.retryWrites: true
coreValidatorURLMock: http://172.20.218.10:30039
customerURL: http://172.30.102.21:30056
customerProductURL: http://172.30.102.21:30057
productDirectoryURL: http://172.20.218.10:30038/product-directory/product/
mailServiceURL: 172.30.102.21:30058
userMail: atulado@grupobisa.com
smtpHost: 172.20.102.30
smtpPort: 25
ccMail:  nrquispe@grupobisa.com
linkMail: http://z0pbirs01.grupobisa.net/Reports/powerbi/Gestion%20de%20Operaciones/Cartera/ResumenEjecutivoTcDigital?rs:embed=true
attachment: false
retryMail: 3
retryTimeMail: 0 0 8,14 * * *
#  spring
spring:
  data:
    mongodb:
      uri: mongodb://admin:mongoPassword@10.42.1.144:27017/db_bian?authSource=admin&w=majority&retryWrites=true
  cloud:
    bus:
      enabled: true
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
      refresh:
        enabled: true 
axon:
  event:
    store:
      database: partyReferenceDataEventStoreEnv
  uri:
    mongo: mongodb://admin:mongoPassword@10.42.1.144:27017/db_bian?authSource=admin&w=majority&retryWrites=true

error:
  package: com.bisa.partyreferencedatadirectory.partyreferencedatacommand
