mongo.username: admin
mongo.password: mongoPassword
mongo.database: db_bian
mongo.host: 172.20.218.10
mongo.port: 30044
mongo.connectionTimeoutMS: 30000
mongo.socketTimeoutMS: 60000
mongo.authSource: admin
mongo.w: majority
mongo.retryWrites: true
spring:
  #   autoconfigure:
  #     exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    bus:
      enabled: true
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
      refresh:
        enabled: true 
axon:
  event:
    store:
      database: partyReferenceDataEventStoreEnv
  uri:
    mongo: mongodb://admin:mongoPassword@10.42.1.167:27017/db_bian?authSource=admin&w=majority&retryWrites=true

error:
  package: com.bisa.partyreferencedatadirectory.partyreferencedatacommand
