spring:
#   autoconfigure:
#     exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://elmer:8321673@cluster0.kygkh.mongodb.net/db_bian?retryWrites=true&w=majority

axon:
 event:
  store:
   database: partyReferenceDataEventStoreEnv
 uri:
  mongo: mongodb+srv://elmer:8321673@cluster0.kygkh.mongodb.net/db_bian?retryWrites=true&w=majority

error:
  package: com.bisa.partyreferencedatadirectory.partyreferencedatacommand
